### PR TITLE
Add options for buster and bullseye in mirror list

### PR DESCRIPTION
**Pull request by cycool29**

### CODE REVIEW

**Comment by Botspot** [comment]
Something's fishy with your size numbers...
See the RPiOS full and twisteros sizes.

**Comment by cycool29** [comment]
I got the values with 

```bash
wget -qO- "https://downloads.raspberrypi.org/raspios_full_armhf_latest" | dd bs=1M count=1 2>/dev/null | busybox unzip -lq - 2>/dev/null | sed -n '3p' | awk '{print $1}'
```

and

```bash
wget -qO- "https://archive.org/download/twister-osv-1-9-2/TwisterOSv1-9-2.zip" | dd bs=1M count=1 2>/dev/null | busybox unzip -lq - 2>/dev/null | sed -n '3p' | awk '{print $1}'
```

I checked again and the values are correct.

**Comment by Botspot** [comment]
Raspberry Pi OS Full 32-bit (bullseye)	4294967295
Raspberry Pi OS Full 32-bit (buster)	4294967295
Twister OS 1.9.2	4294967295

What are the odds?

**Comment by Botspot** [comment]
Okay I ended up doing it the hard way. ;)
```
wget -qO- "https://downloads.raspberrypi.org/raspios_full_armhf/images/raspios_full_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-full.zip" | bsdtar -xvf - -O | wc -c
```
8602517504 bytes for RPiOS full.

**Comment by Botspot** [comment]
TwisterOS took *forever*... but now we have accurate sizes.

**Pull request merged**
