### PR TITLE
Add a FUNDING.yml file

### LINKED ISSUE #5: Sponsorship options
Is there a way to fund this project? It's likely useful for [my business](https://tinypilotkvm.com), so I'd be interested in funding its development.

### PR DESCRIPTION
**Pull request by mtlynch**
This allows users to easily provide financial support for the project.

Fixes #5

### CODE REVIEW

**Comment by Botspot** [comment]
How come you decided to put FUNDING.yml in a new folder called .github?

**Comment by mtlynch** [comment]
It's the naming that Github requires to show a Sponsor link in the repo. You can activate it by checking this box in the repo settings:

image

**Comment by Botspot** [comment]
Oh, I see. Just clicked that box, and sure enough - github found the link and added a Sponsor button.
But here's the problem: now every time someone downloads the repo, their Pi will receive an entirely new unnecessary folder and file. And I don't particularly like that because it increases clutter.
On the other hand - most file managers will keep that folder hidden by default, so maybe it't not that big of a deal.

**Comment by mtlynch** [comment]
>But here's the problem: now every time someone downloads the repo, their Pi will receive an entirely new unnecessary folder and file. And I don't particularly like that because it increases clutter.

It's entirely up to you. One alternative is to just explain how to donate in the README. But it's [super common](https://github.com/search?q=other+filename%3AFUNDING.yml&type=Code&ref=advsearch&l=&l=), and I don't think users mind the extra folder.

**Pull request merged**
